---
title: Build a Python Web Server with Flask
hero_image: images/banner.png
description: Install the Python web framework Flask and set up a basic web server with different pages
original_url: https://raspberrypi.org/learning/python-web-server-with-flask
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: python, html-css-javascript
site_areas: projects
hardware: ''
software: python, html-css-javascript
version: 4.1
last_tested: 2018-08-02
steps: 
- title: Introduction
- title: Build a Flask website
- title: Add a new page
- title: Using HTML
- title: "Challenge: Add a HTML template to your 2nd page"
  challenge: true
- title: Add colour with CSS
- title: Adding dynamic content
- title: What next?
