"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_API_TOKEN"
base_path: "."
base_url: "https://api.crowdin.com"
preserve_hierarchy: true

files:
  - source: /en/**/*.*
    translation: /%locale%/**/%original_file_name%
    ignore:
      - /en/**/*.pdf
      - /en/**/*.mp3
      - /en/**/*.zip
